version: "3"
services:
  pg:
    image: postgres:latest
    shm_size: 1g
    hostname: pg
    container_name: pg
    environment:
      POSTGRES_DB: graphql
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8080:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json

  # elasticsearch:
  #     image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
  #     container_name: elasticsearch
  #     environment:
  #         - cluster.name=docker-cluster
  #         - node.name=elasticsearch-node-1
  #         - network.host=0.0.0.0
  #         - discovery.seed_hosts=elasticsearch
  #         - discovery.type=single-node
  #         - xpack.security.enabled=false
  #     ports:
  #         - "9200:9200"
  #     volumes:
  #         - elasticsearch-data:/usr/share/elasticsearch/data
  #     ulimits:
  #         memlock:
  #             soft: -1
  #             hard: -1

volumes:
  pg:
  pgadmin:
  # elasticsearch-data:
